Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/alembic/config.py", line 1022, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.11/dist-packages/alembic/config.py", line 1012, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.11/dist-packages/alembic/config.py", line 946, in run_cmd
    fn(
  File "/usr/local/lib/python3.11/dist-packages/alembic/command.py", line 709, in current
    script.run_env()
  File "/usr/local/lib/python3.11/dist-packages/alembic/script/base.py", line 549, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.11/dist-packages/alembic/util/pyfiles.py", line 116, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/alembic/util/pyfiles.py", line 136, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/morningai-mvp/apps/api/alembic/env.py", line 94, in <module>
    run_migrations_online()
  File "/home/ubuntu/morningai-mvp/apps/api/alembic/env.py", line 76, in run_migrations_online
    connectable = engine_from_config(
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/create.py", line 838, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/create.py", line 564, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/url.py", line 856, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/url.py", line 917, in _parse_url
    components["port"] = int(components["port"])
                         ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'port'
